[package]
name = "gptcommit"
version = "0.1.1"
edition = "2021"
authors = ["Roger Zurawicki <roger@zura.wiki>"]
description = "A git prepare-commit-msg hook for summarizing commits with GPT-3."
readme = "README.md"
license = "MIT"
repository = "https://github.com/zurawiki/gptcommit"

[[bin]]
name = "gptcommit"
path = "src/main.rs"

[dependencies]
ansi_term = "0.12.1"
anyhow = "1.0.68"
clap = { version = "4.1.1", features = ["derive"] }
futures = "0.3.25"
log = "0.4.17"
rayon = "1.6.1"
reqwest = { version = "0.11.13", features = ["json"] }
serde_json = "1.0.91"
simple_logger = "4.0.0"
tokio = { version = "1.24.1", features = ["full"] }
which = "4.3.0"

[dev-dependencies]
cargo-edit = "0.11.7"
toml-cli = "0.2.3"
