name: CI

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: '37 6 * * 1-5'  # run once per day Monday-Friday at 7:37am

env:
  RUST_BACKTRACE: 1
  CARGO_TERM_COLOR: always

jobs:
  just:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        just_cmd:
          - "build"
          - "test"
        include:
          - os: ubuntu-latest
            just_cmd: lint
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
      - uses: extractions/setup-just@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: just ${{ matrix.just_cmd }}

  ci-everything:
    name: All CI stages
    runs-on: ubuntu-latest
    needs:
      - lint
      - rust-tests
      - run-on-bevy-gltf
    steps:
      - run: exit 0

  lint:
    name: Check lint and rustfmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
          profile: minimal
          override: true

      - uses: Swatinem/rust-cache@v2

      - name: cargo clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --workspace --all-features --all-targets -- -D warnings --allow deprecated

      - name: cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check

  rust-tests:
    name: Run tests
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        toolchain: ["stable", "beta"]
        experimental: [false]
        include:
          - toolchain: "nightly"
            experimental: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          profile: minimal
          override: true

      - uses: Swatinem/rust-cache@v2

      - name: compile
        run: cargo test --no-run

      - name: test
        run: cargo test

  run-on-bevy-gltf:
    # cargo-semver-checks reported false-positives since it did not include
    # features defined implicitly via optional dependencies:
    # https://github.com/obi1kenobi/cargo-semver-checks/issues/265
    name: Run cargo-semver-checks on bevy_gltf v0.9.1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout cargo-semver-checks
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Checkout bevy
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          repository: 'bevyengine/bevy'
          ref: 'v0.9.1'
          path: 'subject'

      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - uses: Swatinem/rust-cache@v2

      - name: Run semver-checks
        run: cargo run semver-checks check-release --manifest-path="subject/crates/bevy_gltf/Cargo.toml" --baseline-version 0.9.0

  init-release:
    name: Run the release workflow
    needs:
      - should-publish
      - ci-everything
      - pre-publish-checks
    if: needs.should-publish.outputs.is_new_version == 'yes' && github.ref == 'refs/heads/main'
    uses: ./.github/workflows/release.yml
    with:
      publish-tag: ${{ needs.should-publish.outputs.publish-tag }}
    secrets:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

  should-publish:
    name: Check if version changed
    runs-on: ubuntu-latest
    outputs:
      is_new_version: ${{ steps.check.outputs.is_new_version }}
      publish-tag: ${{ steps.tag.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - uses: Swatinem/rust-cache@v2

      - id: check
        run: |
          set +e
          ./scripts/is_version_already_uploaded.sh cargo-semver-checks
          export EXIT_CODE="$?"
          set -e
          if [[ "$EXIT_CODE" == "7" ]]; then
            echo '::set-output name=is_new_version::no'
          elif [[ "$EXIT_CODE" == "0" ]]; then
            echo '::set-output name=is_new_version::yes'
          else
            # Unexpected outcome, indicates a bug.
            exit "$EXIT_CODE"
          fi
      - name: Determine the tag name
        id: tag
        run: |
          export TAG_NAME="v$(./scripts/get_current_version.sh cargo-semver-checks)"
          echo "tag=$TAG_NAME" >> $GITHUB_OUTPUT

pre-publish-checks:
    name: Check for semver compliance
    runs-on: ubuntu-latest
    needs:
      - ci-everything
      - should-publish
    if: needs.should-publish.outputs.is_new_version == 'yes'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Check semver
        uses: obi1kenobi/cargo-semver-checks-action@v1
        with:
          # cargo-semver-checks currently doesn't have a --lib target,
          # so we explicitly ask for the binary target to be checked instead.
          # For library crates, you almost always want the default `--lib` value here.
          crate-target: --bin cargo-semver-checks
